-- =====================================================================
-- Game Spot Reservas — Esquema de la base de datos (PostgreSQL / Supabase)
--
-- Este archivo es la única fuente de verdad del esquema:
--   * En Supabase se ejecuta a mano en el SQL Editor.
--   * En las pruebas, Testcontainers lo carga al iniciar el contenedor.
-- Spring Boot NO crea tablas (ddl-auto: validate); solo verifica que las
-- entidades coincidan con este esquema.
--
-- Convenciones (ESTANDARES.md):
--   * Tablas en snake_case plural; entidades Java en PascalCase singular.
--   * La unidad va en el nombre: _pesos, _centavos, _minutos.
--   * Los booleanos se leen como pregunta: esta_, tiene_, fue_.
--   * Los estados se guardan en MAYÚSCULA, igual que el nombre del enum en
--     Java, para usar @Enumerated(EnumType.STRING) sin convertidores.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 0. Extensiones y funciones comunes
-- ---------------------------------------------------------------------

-- Supabase ya trae el esquema "extensions"; en un Postgres normal se crea.
create schema if not exists extensions;

-- Necesaria para la restricción que impide dobles reservas (riesgo R4).
create extension if not exists btree_gist with schema extensions;

-- Mantiene actualizado_en al día en cada UPDATE.
create or replace function public.marcar_actualizado_en()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.actualizado_en := now();
  return new;
end;
$$;


-- ---------------------------------------------------------------------
-- 1. Usuarios (coincide con model/Usuario.java del login con JWT)
-- ---------------------------------------------------------------------

create table public.usuarios (
  id                bigint generated by default as identity primary key,
  nombre            text not null,
  email             text not null unique,
  password_hash     text not null,
  rol               text not null default 'CLIENTE'
                    check (rol in ('CLIENTE', 'ADMIN')),
  -- Saldo de puntos. Lo mantiene el trigger de movimientos_puntos;
  -- el backend solo lo lee.
  puntos_fidelidad  integer not null default 0 check (puntos_fidelidad >= 0),
  fecha_registro    timestamptz not null default now()
);


-- ---------------------------------------------------------------------
-- 2. Catálogo del negocio: modalidades, equipos, horarios, configuración
-- ---------------------------------------------------------------------

-- Modalidad = tipo de servicio con su tarifa (Xbox 360, Series S, Sala VIP).
create table public.modalidades (
  id                 bigint generated by default as identity primary key,
  nombre             text not null unique,
  descripcion        text,
  tarifa_hora_pesos  integer not null check (tarifa_hora_pesos > 0),
  esta_activa        boolean not null default true,
  creado_en          timestamptz not null default now(),
  actualizado_en     timestamptz not null default now()
);

create trigger modalidades_actualizado_en
before update on public.modalidades
for each row execute function public.marcar_actualizado_en();

-- Equipo = consola o sala física que se reserva.
create table public.equipos (
  id               bigint generated by default as identity primary key,
  modalidad_id     bigint not null references public.modalidades (id),
  nombre           text not null unique,          -- p. ej. "Xbox 360 #1"
  esta_disponible  boolean not null default true, -- false = fuera de servicio
  creado_en        timestamptz not null default now(),
  actualizado_en   timestamptz not null default now()
);

create index equipos_modalidad_idx on public.equipos (modalidad_id);

create trigger equipos_actualizado_en
before update on public.equipos
for each row execute function public.marcar_actualizado_en();

-- Horario de atención por día (1 = lunes ... 7 = domingo, como DayOfWeek).
-- Nota: si el local cierra después de medianoche, hay que ajustar el CHECK.
create table public.horarios_atencion (
  id             bigint generated by default as identity primary key,
  dia_semana     smallint not null unique check (dia_semana between 1 and 7),
  hora_apertura  time not null,
  hora_cierre    time not null,
  constraint horarios_cierre_despues_apertura check (hora_cierre > hora_apertura),
  constraint horarios_en_bloques_30_min check (
    extract(minute from hora_apertura) in (0, 30)
    and extract(minute from hora_cierre) in (0, 30)
  )
);

-- Parámetros del negocio en una sola fila (id siempre = 1).
create table public.configuracion_negocio (
  id                    smallint primary key default 1 check (id = 1),
  valor_adelanto_pesos  integer not null check (valor_adelanto_pesos > 0),
  puntos_por_hora       integer not null check (puntos_por_hora >= 0),
  -- Minutos que se aparta el bloque mientras el cliente paga en Wompi.
  minutos_espera_pago   integer not null default 15
                        check (minutos_espera_pago between 5 and 60),
  actualizado_en        timestamptz not null default now()
);

create trigger configuracion_negocio_actualizado_en
before update on public.configuracion_negocio
for each row execute function public.marcar_actualizado_en();


-- ---------------------------------------------------------------------
-- 3. Reservas por bloques de 30 minutos
-- ---------------------------------------------------------------------
-- Ciclo de vida:
--   PENDIENTE_PAGO -> CONFIRMADA -> COMPLETADA
--   PENDIENTE_PAGO -> EXPIRADA   (no pagó a tiempo)
--   PENDIENTE_PAGO | CONFIRMADA -> CANCELADA (admin)
--
-- Reglas que garantiza la base de datos (no solo el backend):
--   * Bloques alineados a :00 o :30 y duración múltiplo de 30 minutos.
--   * Ningún equipo puede tener dos reservas activas que se crucen
--     (objetivo 1: cero dobles reservas, también con peticiones simultáneas).
--   * Una reserva confirmada o completada siempre tiene adelanto pagado
--     (objetivo 2: 100 % de reservas confirmadas con adelanto).

create table public.reservas (
  id                     bigint generated by default as identity primary key,
  usuario_id             bigint not null references public.usuarios (id),
  equipo_id              bigint not null references public.equipos (id),
  inicio                 timestamptz not null,
  fin                    timestamptz not null,
  -- Valores del momento de reservar, por si la tarifa cambia después.
  precio_total_pesos     integer not null check (precio_total_pesos > 0),
  adelanto_pesos         integer not null check (adelanto_pesos > 0),
  estado                 text not null default 'PENDIENTE_PAGO'
                         check (estado in ('PENDIENTE_PAGO', 'CONFIRMADA',
                                           'COMPLETADA', 'CANCELADA', 'EXPIRADA')),
  tiene_anticipo_pagado  boolean not null default false,
  expira_en              timestamptz,  -- límite para pagar si está PENDIENTE_PAGO
  cancelada_en           timestamptz,
  motivo_cancelacion     text,
  creado_en              timestamptz not null default now(),
  actualizado_en         timestamptz not null default now(),

  constraint reservas_fin_despues_inicio check (fin > inicio),

  -- Colombia es UTC-5 sin horario de verano: los minutos en UTC coinciden
  -- con los de Bogotá.
  constraint reservas_bloques_30_min check (
    extract(minute from (inicio at time zone 'UTC')) in (0, 30)
    and extract(second from (inicio at time zone 'UTC')) = 0
    and extract(epoch from (fin - inicio))::integer % 1800 = 0
  ),

  constraint reservas_adelanto_no_supera_total
    check (adelanto_pesos <= precio_total_pesos),

  constraint reservas_confirmada_requiere_adelanto check (
    estado not in ('CONFIRMADA', 'COMPLETADA') or tiene_anticipo_pagado
  ),

  constraint reservas_cancelada_tiene_fecha check (
    estado <> 'CANCELADA' or cancelada_en is not null
  ),

  constraint reservas_pendiente_tiene_expiracion check (
    estado <> 'PENDIENTE_PAGO' or expira_en is not null
  ),

  -- Impide dobles reservas: dos reservas activas del mismo equipo no pueden
  -- solaparse. '[)' permite 15:00-16:00 seguida de 16:00-17:00.
  constraint reservas_sin_cruces exclude using gist (
    equipo_id with =,
    tstzrange(inicio, fin, '[)') with &&
  ) where (estado in ('PENDIENTE_PAGO', 'CONFIRMADA', 'COMPLETADA'))
);

create index reservas_historial_usuario_idx on public.reservas (usuario_id, inicio desc);
create index reservas_pendientes_idx on public.reservas (expira_en)
  where estado = 'PENDIENTE_PAGO';

create trigger reservas_actualizado_en
before update on public.reservas
for each row execute function public.marcar_actualizado_en();

-- Libera los bloques de reservas que no se pagaron a tiempo y devuelve
-- cuántas expiraron. Se llama desde un @Scheduled de Spring Boot.
create or replace function public.expirar_reservas_pendientes()
returns integer
language sql
set search_path = ''
as $$
  with expiradas as (
    update public.reservas
       set estado = 'EXPIRADA'
     where estado = 'PENDIENTE_PAGO'
       and expira_en < now()
    returning 1
  )
  select count(*)::integer from expiradas;
$$;


-- ---------------------------------------------------------------------
-- 4. Pagos de adelanto con Wompi
-- ---------------------------------------------------------------------
-- Wompi trabaja con montos en centavos (amount_in_cents).
-- NUNCA guardar llaves de Wompi ni datos de tarjeta en esta tabla.

create table public.pagos (
  id                    bigint generated by default as identity primary key,
  reserva_id            bigint not null references public.reservas (id),
  referencia            text not null unique,  -- referencia que enviamos a Wompi
  id_transaccion_wompi  text unique,           -- id que devuelve Wompi
  monto_centavos        bigint not null check (monto_centavos > 0),
  moneda                text not null default 'COP' check (moneda = 'COP'),
  estado                text not null default 'PENDIENTE'
                        check (estado in ('PENDIENTE', 'APROBADO', 'RECHAZADO',
                                          'ANULADO', 'ERROR')),
  metodo_pago           text,   -- CARD, NEQUI, PSE, BANCOLOMBIA_TRANSFER...
  respuesta_wompi       jsonb,  -- último evento recibido del webhook
  creado_en             timestamptz not null default now(),
  actualizado_en        timestamptz not null default now()
);

create index pagos_reserva_idx on public.pagos (reserva_id);

-- Una reserva no puede tener dos pagos aprobados.
create unique index pagos_un_aprobado_por_reserva
  on public.pagos (reserva_id) where estado = 'APROBADO';

create trigger pagos_actualizado_en
before update on public.pagos
for each row execute function public.marcar_actualizado_en();

-- Cuando un pago pasa a APROBADO, confirma la reserva, siempre que siga
-- pendiente y el monto cubra el adelanto. Si la reserva ya expiró, no se
-- confirma: el admin la verá en el panel con el pago aprobado.
create or replace function public.confirmar_reserva_al_aprobar_pago()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.estado = 'APROBADO'
     and (tg_op = 'INSERT' or old.estado is distinct from 'APROBADO') then
    update public.reservas
       set estado = 'CONFIRMADA',
           tiene_anticipo_pagado = true,
           expira_en = null
     where id = new.reserva_id
       and estado = 'PENDIENTE_PAGO'
       and new.monto_centavos >= adelanto_pesos::bigint * 100;
  end if;
  return new;
end;
$$;

create trigger pagos_confirmar_reserva
after insert or update of estado on public.pagos
for each row execute function public.confirmar_reserva_al_aprobar_pago();


-- ---------------------------------------------------------------------
-- 5. Fidelización: puntos por horas jugadas
-- ---------------------------------------------------------------------

create table public.movimientos_puntos (
  id           bigint generated by default as identity primary key,
  usuario_id   bigint not null references public.usuarios (id),
  reserva_id   bigint references public.reservas (id),
  puntos       integer not null check (puntos <> 0),
  tipo         text not null check (tipo in ('HORAS_JUGADAS', 'AJUSTE_ADMIN')),
  descripcion  text,
  creado_en    timestamptz not null default now()
);

create index movimientos_puntos_usuario_idx on public.movimientos_puntos (usuario_id);

-- Los puntos de una reserva se otorgan una sola vez.
create unique index movimientos_puntos_una_vez_por_reserva
  on public.movimientos_puntos (reserva_id) where tipo = 'HORAS_JUGADAS';

-- Cada movimiento suma (o resta) al saldo del usuario. El CHECK de
-- usuarios.puntos_fidelidad impide que el saldo quede negativo.
create or replace function public.actualizar_puntos_fidelidad()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  update public.usuarios
     set puntos_fidelidad = puntos_fidelidad + new.puntos
   where id = new.usuario_id;
  return new;
end;
$$;

create trigger movimientos_puntos_actualizar_saldo
after insert on public.movimientos_puntos
for each row execute function public.actualizar_puntos_fidelidad();

-- Al marcar una reserva como COMPLETADA, otorga los puntos según
-- configuracion_negocio.puntos_por_hora (proporcional a los minutos).
create or replace function public.otorgar_puntos_al_completar()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_puntos_por_hora   integer;
  v_duracion_minutos  integer;
  v_puntos            integer;
begin
  if new.estado = 'COMPLETADA' and old.estado is distinct from 'COMPLETADA' then
    select puntos_por_hora into v_puntos_por_hora
      from public.configuracion_negocio
     where id = 1;

    v_duracion_minutos := extract(epoch from (new.fin - new.inicio))::integer / 60;
    v_puntos := floor(v_duracion_minutos * coalesce(v_puntos_por_hora, 0) / 60.0);

    if v_puntos > 0 then
      insert into public.movimientos_puntos
        (usuario_id, reserva_id, puntos, tipo, descripcion)
      values
        (new.usuario_id, new.id, v_puntos, 'HORAS_JUGADAS',
         v_duracion_minutos || ' minutos jugados')
      on conflict do nothing;
    end if;
  end if;
  return new;
end;
$$;

create trigger reservas_otorgar_puntos
after update of estado on public.reservas
for each row execute function public.otorgar_puntos_al_completar();


-- ---------------------------------------------------------------------
-- 6. Notificaciones automáticas (confirmación y recordatorio)
-- ---------------------------------------------------------------------

create table public.notificaciones (
  id               bigint generated by default as identity primary key,
  usuario_id       bigint not null references public.usuarios (id),
  reserva_id       bigint references public.reservas (id),
  tipo             text not null check (tipo in ('CONFIRMACION', 'RECORDATORIO')),
  canal            text not null default 'CORREO' check (canal in ('CORREO', 'PUSH')),
  programada_para  timestamptz not null default now(),
  fue_enviada      boolean not null default false,
  enviada_en       timestamptz,
  intentos         integer not null default 0 check (intentos >= 0),
  ultimo_error     text,
  creado_en        timestamptz not null default now(),
  constraint notificaciones_enviada_tiene_fecha
    check (not fue_enviada or enviada_en is not null)
);

create index notificaciones_por_enviar_idx on public.notificaciones (programada_para)
  where not fue_enviada;


-- ---------------------------------------------------------------------
-- 7. Seguridad (Row Level Security)
-- ---------------------------------------------------------------------
-- RLS activado sin políticas: la API pública de Supabase (anon key) no puede
-- leer ni escribir nada. Spring Boot se conecta directo a Postgres con el
-- usuario de la base de datos, que no queda limitado por RLS.

alter table public.usuarios              enable row level security;
alter table public.modalidades           enable row level security;
alter table public.equipos               enable row level security;
alter table public.horarios_atencion     enable row level security;
alter table public.configuracion_negocio enable row level security;
alter table public.reservas              enable row level security;
alter table public.pagos                 enable row level security;
alter table public.movimientos_puntos    enable row level security;
alter table public.notificaciones        enable row level security;


-- ---------------------------------------------------------------------
-- 8. Datos iniciales
-- ---------------------------------------------------------------------

-- Tarifas del acta de constitución.
insert into public.modalidades (nombre, tarifa_hora_pesos) values
  ('Xbox 360', 5000),
  ('Xbox Series S', 6000),
  ('Sala VIP Xbox Series X', 7000);

-- AJUSTAR: un equipo por modalidad como punto de partida; reemplazar con el
-- número real de consolas que entregue el propietario.
insert into public.equipos (modalidad_id, nombre)
select id, nombre || ' #1' from public.modalidades order by id;

-- AJUSTAR: valores de EJEMPLO, pendientes de confirmar con el propietario.
insert into public.configuracion_negocio
  (valor_adelanto_pesos, puntos_por_hora, minutos_espera_pago)
values
  (2000, 10, 15);

-- AJUSTAR: horario de atención real. Ejemplo:
-- insert into public.horarios_atencion (dia_semana, hora_apertura, hora_cierre) values
--   (1, '14:00', '22:00'), (2, '14:00', '22:00'), (3, '14:00', '22:00'),
--   (4, '14:00', '22:00'), (5, '14:00', '23:00'), (6, '10:00', '23:00'),
--   (7, '10:00', '21:00');
